repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
        files: ^(?!(\.clang-format)$)
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix, --indent, '   ', --no-ensure-ascii, --no-sort-keys]
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ['-iii', '-ll']
        stages:
        -   push
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: local
    hooks:
    -   id: django-check
        name: Check django project for potential errors
        entry: sh -c ". django_venv/bin/activate && python manage.py check --deploy"
        types:
        -   python
        pass_filenames: false
        language: system
